<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Задача-1" data-toc-modified-id="Задача-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Задача 1</a></span></li><li><span><a href="#Задача-2" data-toc-modified-id="Задача-2-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Задача 2</a></span></li><li><span><a href="#Задача-3" data-toc-modified-id="Задача-3-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Задача 3</a></span></li><li><span><a href="#Задача-4" data-toc-modified-id="Задача-4-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Задача 4</a></span></li><li><span><a href="#Задача-5" data-toc-modified-id="Задача-5-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Задача 5</a></span></li></ul></div>

<a href="https://colab.research.google.com/github/VorobyvEgor/Machine_Learning_Sber/blob/main/Deep_lerning/PyTorch_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Задача 1

1) Создайте два вещественных тензора: a размером (3, 4) и b размером (12,)

2) Создайте тензор c, являющийся тензором b, но размера (2, 2, 3)

3) Выведите первый столбец матрицы a с помощью индексации 

In [3]:
a = torch.FloatTensor(3, 4)
b = torch.FloatTensor(12)

In [4]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
b

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
c = b.view(2, 2, 3)

In [7]:
c

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
a[:, 0]

tensor([0., 0., 0.])

# Задача 2

1) Создайте два вещественных тензора: a размером (5, 2) и b размером (1,10)

2) Создайте тензор c, являющийся тензором b, но размера (5, 2)

3) Произведите все арифметические операции с тензорами a и c 

In [15]:
a = torch.FloatTensor(5, 2)
b = torch.FloatTensor(1, 10)

In [17]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
b

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
c = b.view(5, 2)

In [19]:
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
a.add(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
a.sub(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
a.mul(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
a.div(c)

tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]])

# Задача 3

1) Создайте тензор целых чисел images размерности (100, 200, 200, 3) (можно интерпретировать это как 100 картинок размера 200х200 с тремя цветовыми каналами, то есть 100 цветных изображений 200х200). Заполните его нулями

2) Сделайте так, чтобы у i-ой по порядку картинки была нарисована белая полоса толщиной два пикселя в строках, которые соответствуют номеру картинки. Например, у 3-ей по порядку картинки белая полоска будет занимать 6 и 7 строки, у 99 -- 198 и 199. Сделать белую строку можно, записав в ячейки тензора число 255 (по всем трём каналам). Выведите пару примеров с помощоью pylot

3) Посчитайте среднее тензора images по 1-ой оси (по сути - средняя картинка), умножьте полученный тензор на 70. Нарисуйте с помощью pyplot, должна получиться серая картинка (при взятии среднего нужно привести тензор к float с помощью .float(), при отрисовке обратно к int с помощью .int())

In [24]:
images = torch.FloatTensor(100, 200, 200, 3)

In [25]:
images

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

# Задача 4

Напишите функцию forward_pass(X, w) (w0 входит в w) для одного нейрона (с сигмоидой) с помощью PyTorch

In [26]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

# Задача 5

1) Перейдите на Google Colaboratory, чтобы работать с GPU. Загрузите туда этот ноутбук (Upload notebook)

2) В Colab нажмите в меню сверху: Runtime -> Change Runtime Type -> GPU, где изначально стоит None

3) Объявите тензор a размера (2, 3, 4) и тензор b размера (1, 8, 3) на GPU, иницилизируйте их случайно равномерно (.uniform_())

4) Затем измените форму тензора b, чтобы она совпадала с формой тензора a, получите тензор c

5) Переместите c на CPU, переместите a на CPU

6) Оберните их в Variable()

7) Объявите тензор L = torch.mean((c - a)**2) и посчитайте градиент L по c ( то есть ∂L∂c)

8) Выведите градиент L по c