<a href="https://colab.research.google.com/github/VorobyvEgor/Machine_Learning_Sber/blob/main/Deep_lerning/PyTorch_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Задача-1" data-toc-modified-id="Задача-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Задача 1</a></span></li><li><span><a href="#Задача-2" data-toc-modified-id="Задача-2-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Задача 2</a></span></li><li><span><a href="#Задача-3" data-toc-modified-id="Задача-3-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Задача 3</a></span></li><li><span><a href="#Задача-4" data-toc-modified-id="Задача-4-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Задача 4</a></span></li><li><span><a href="#Задача-5" data-toc-modified-id="Задача-5-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Задача 5</a></span></li></ul></div>

<a href="https://colab.research.google.com/github/VorobyvEgor/Machine_Learning_Sber/blob/main/Deep_lerning/PyTorch_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Задача 1

1) Создайте два вещественных тензора: a размером (3, 4) и b размером (12,)

2) Создайте тензор c, являющийся тензором b, но размера (2, 2, 3)

3) Выведите первый столбец матрицы a с помощью индексации 

In [ ]:
a = torch.FloatTensor(3, 4)
b = torch.FloatTensor(12)

In [ ]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
b

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
c = b.view(2, 2, 3)

In [ ]:
c

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
a[:, 0]

tensor([0., 0., 0.])

# Задача 2

1) Создайте два вещественных тензора: a размером (5, 2) и b размером (1,10)

2) Создайте тензор c, являющийся тензором b, но размера (5, 2)

3) Произведите все арифметические операции с тензорами a и c 

In [ ]:
a = torch.FloatTensor(5, 2)
b = torch.FloatTensor(1, 10)

In [ ]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
b

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
c = b.view(5, 2)

In [ ]:
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a.add(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a.sub(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a.mul(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a.div(c)

tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]])

# Задача 3

1) Создайте тензор целых чисел images размерности (100, 200, 200, 3) (можно интерпретировать это как 100 картинок размера 200х200 с тремя цветовыми каналами, то есть 100 цветных изображений 200х200). Заполните его нулями

2) Сделайте так, чтобы у i-ой по порядку картинки была нарисована белая полоса толщиной два пикселя в строках, которые соответствуют номеру картинки. Например, у 3-ей по порядку картинки белая полоска будет занимать 6 и 7 строки, у 99 -- 198 и 199. Сделать белую строку можно, записав в ячейки тензора число 255 (по всем трём каналам). Выведите пару примеров с помощоью pylot

3) Посчитайте среднее тензора images по 1-ой оси (по сути - средняя картинка), умножьте полученный тензор на 70. Нарисуйте с помощью pyplot, должна получиться серая картинка (при взятии среднего нужно привести тензор к float с помощью .float(), при отрисовке обратно к int с помощью .int())

In [ ]:
images = torch.FloatTensor(100, 200, 200, 3)

In [ ]:
images

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

# Задача 4

Напишите функцию forward_pass(X, w) (w0 входит в w) для одного нейрона (с сигмоидой) с помощью PyTorch

In [ ]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

# Задача 5

1) Перейдите на Google Colaboratory, чтобы работать с GPU. Загрузите туда этот ноутбук (Upload notebook)

2) В Colab нажмите в меню сверху: Runtime -> Change Runtime Type -> GPU, где изначально стоит None

3) Объявите тензор a размера (2, 3, 4) и тензор b размера (1, 8, 3) на GPU, иницилизируйте их случайно равномерно (.uniform_())

4) Затем измените форму тензора b, чтобы она совпадала с формой тензора a, получите тензор c

5) Переместите c на CPU, переместите a на CPU

6) Оберните их в Variable()

7) Объявите тензор L = torch.mean((c - a)**2) и посчитайте градиент L по c ( то есть ∂L∂c)

8) Выведите градиент L по c

In [3]:
a = torch.FloatTensor(2, 3, 4).uniform_().cuda()
b = torch.FloatTensor(1, 8, 3).uniform_().cuda()

In [7]:
a

tensor([[[0.5123, 0.6577, 0.4691, 0.1562],
         [0.2997, 0.8640, 0.2368, 0.1877],
         [0.5382, 0.6140, 0.1099, 0.4007]],

        [[0.9599, 0.6723, 0.2140, 0.7519],
         [0.8527, 0.1882, 0.0713, 0.4621],
         [0.9612, 0.1674, 0.9916, 0.4133]]], device='cuda:0')

In [8]:
b

tensor([[[0.6811, 0.3410, 0.0021],
         [0.6635, 0.6862, 0.7827],
         [0.4912, 0.3741, 0.6585],
         [0.5743, 0.5626, 0.1142],
         [0.3306, 0.4099, 0.5106],
         [0.6547, 0.4032, 0.8604],
         [0.1709, 0.6635, 0.6850],
         [0.7519, 0.9846, 0.7103]]], device='cuda:0')

In [4]:
c = b.view(a.size())

In [5]:
c

tensor([[[0.6811, 0.3410, 0.0021, 0.6635],
         [0.6862, 0.7827, 0.4912, 0.3741],
         [0.6585, 0.5743, 0.5626, 0.1142]],

        [[0.3306, 0.4099, 0.5106, 0.6547],
         [0.4032, 0.8604, 0.1709, 0.6635],
         [0.6850, 0.7519, 0.9846, 0.7103]]], device='cuda:0')

In [10]:
c.is_cuda

True

In [12]:
c = c.cpu()
a = a.cpu()

In [13]:
from torch.autograd import Variable

In [14]:
c = Variable(c, requires_grad=True)
a = Variable(a, requires_grad=True)

In [15]:
L = torch.mean((c - a)**2)

In [16]:
L.backward()

In [18]:
c.grad

tensor([[[ 0.0141, -0.0264, -0.0389,  0.0423],
         [ 0.0322, -0.0068,  0.0212,  0.0155],
         [ 0.0100, -0.0033,  0.0377, -0.0239]],

        [[-0.0524, -0.0219,  0.0247, -0.0081],
         [-0.0375,  0.0560,  0.0083,  0.0168],
         [-0.0230,  0.0487, -0.0006,  0.0248]]])